### PR TITLE
Use Go modules

### PR DESCRIPTION
**Pull request by hwh33**
The tests are failing, but at least they build now =)

### CODE REVIEW

**Comment by hwh33** [comment]
Hmm never mind, not building on CircleCI.  That's weird.  I'll look at that.

**Comment by hwh33** [comment]
Okay, _now_ it's building.  Also TIL how to SSH into a CircleCI build.  Cool stuff!

**Review by max-b — APPROVED** [review]
Thanks @hwh33 !! Honestly I think we could just merge this into master for now, it's a nice improvement, but either way is good.

Do we generally just have the green light to upgrade older go code to use modules? Is there anything in that transition to be aware of or is it basically just good to go?

**Comment by max-b** [comment]
Oh funny I was looking at the previous commit and this branch/the previous commit was actually autogenerated by CircleCI. I was actually working on it at https://github.com/getlantern/fronted/tree/maxb/circleci, but I think at this point it's fine either way. +1

**Comment by hwh33** [comment]
Merging to master sounds good to me since the tests are failing locally too.

Yes, in fact I think we should generally be pretty proactive about upgrading older code to use modules.  I previously converted all Go code using older package managers (e.g. glide) to modules, so any module-less code right now has no package management.  The longer a given codebase sits without package management, the harder it becomes IMO to track down the versions that code expects from each of its dependencies.  I don't think we have any official policy on doing that though.

**Comment by hwh33** [comment]
> Oh funny I was looking at the previous commit and this branch/the previous commit was actually autogenerated by CircleCI. I was actually working on it at https://github.com/getlantern/fronted/tree/maxb/circleci

Ohh. Heh, that explains it.  I think we should use your CircleCI config.  I was just making the minimal changes needed to get the code building, but including stuff like test coverage is nice.

**Comment by max-b** [comment]
I went ahead and pulled this in w/ https://github.com/getlantern/fronted/pull/29

**Pull request closed without merging**
