### PR TITLE
Adding SNI to peer certificate verification

### PR DESCRIPTION
**Pull request by WendelHime**
On this pull request I'm adding a `VerifyHost` attribute that shall be used when verifying peer certificates from requests that use the SNI config. Some unit tests were added, some updated with the new parameter and some deprecated libraries from `cache.go` have been replaced.

### CODE REVIEW

**Comment by WendelHime** [comment]
Coveralls is failing but tests are passing

**Review by hwh33 — APPROVED** [review]
Looks great!  Nice work

**Comment by hwh33** [comment]
Not sure why coveralls is returning 405, but let's just ignore that for now.  Merge away!  Could you open a PR to update this in Flashlight?  You can just merge it straight away.

**Comment by WendelHime** [comment]
Looks like they're down: https://status.coveralls.io/

**Pull request merged**
