### PR TITLE
Converting to zap

### PR DESCRIPTION
**Pull request by myleshorton**

### CODE REVIEW

**Comment by oxtoacart** [comment]
@myleshorton I'm a bit confused. The ZapLogger package doesn't appear to support our ops context stuff. Are we intentionally dropping that? I personally find it very useful, in particular in the flashlight program but also in http-proxy.

**Comment by oxtoacart** [comment]
@myleshorton I'm going to work on a golog PR tonight that I think gets you what you want w.r.t. to Zap and preserves the pieces of golog that I think are important.

**Comment by oxtoacart** [comment]
Here's my [golog PR](https://github.com/getlantern/golog/pull/4)

**Comment by myleshorton** [comment]
Closing!

**Pull request closed without merging**
